# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: kitting_arm
  joint_model_group_pose: kitting_home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - linear_arm_actuator_joint
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
    - vacuum_gripper_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: /ariac/kitting/kitting_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
    - linear_arm_actuator_joint
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
    gains:
      linear_arm_actuator_joint:
        p: 10000
        d: 500
        i: 0
        i_clamp: 1
      shoulder_pan_joint:
        p: 10000
        d: 150
        i: 0
        i_clamp: 1
      shoulder_lift_joint:
        p: 50000
        d: 150
        i: 10
        i_clamp: 50
      elbow_joint:
        p: 50000
        d: 150
        i: 1
        i_clamp: 25
      wrist_1_joint:
        p: 100
        d: 5
        i: 0
        i_clamp: 1
      wrist_2_joint:
        p: 75
        d: 2
        i: 0
        i_clamp: 1
      wrist_3_joint:
        p: 25
        d: 1
        i: 0
        i_clamp: 1