sensors:
  logical_camera_bin1:
    type: logical_camera
    pose:
      xyz: [-2.27, 3.37, 1.868509]
      rpy: [1.570797, 1.570792, 1.570796]
  logical_camera_bin2:
    type: logical_camera
    pose:
      xyz: [-2.27, 2.56, 1.868509]
      rpy: [1.570797, 1.570792, 1.570796]
  logical_camera_bin3:
    type: logical_camera
    pose:
      xyz: [-2.27, -2.56, 1.868509]
      rpy: [1.570797, 1.570792, 1.570796]
  logical_camera_bin4:
    type: logical_camera
    pose:
      xyz: [-2.27, -3.37, 1.868509]
      rpy: [1.570797, 1.570792, 1.570796]

  logical_camera_station1:
    type: logical_camera
    pose:
      xyz: [-5.5, -3, 1.868509]
      rpy: [1.570797, 1.570792, 1.570796]

  logical_camera_station2:
    type: logical_camera
    pose:
      xyz: [-5.5, 3, 1.868509]
      rpy: [1.570797, 1.570792, 1.570796]

  logical_camera_station3:
    type: logical_camera
    pose:
      xyz: [-10.5, -3, 1.868509]
      rpy: [1.570797, 1.570792, 1.570796]

  logical_camera_station4:
    type: logical_camera
    pose:
      xyz: [-10.5, 3, 1.868509]
      rpy: [1.570797, 1.570792, 1.570796]


robot_camera:
  enable: false

